package com.danielcurwgmail.posjava;

import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.TextView;
import android.widget.Toast;
import androidx.appcompat.app.AppCompatActivity;

    public class Form1Designer extends AppCompatActivity {
        private Button buttonConnect;
        private Spinner comboBoxComm;
        private TextView label1;
        private TextView label2;
        private EditText textBoxAmount;
        private Button buttonSale;
        private TextView label3;
        private EditText textBoxVoid;
        private Button buttonVoid;
        private EditText textBoxRequest;
        private TextView label4;
        private TextView label11;
        private TextView label10;
        private EditText textBoxRTransactionDate;
        private EditText textBoxRApprovalCode;
        private TextView label12;
        private EditText textBoxRBatchNo;
        private TextView label13;
        private EditText textBoxAccountType;
        private TextView label14;
        private EditText textBoxRCardType;
        private TextView label16;
        private EditText textBoxRTransactionID;
        private TextView label15;
        private EditText textBoxRInvoiceNumber;
        private TextView label9;
        private EditText textBoxRTerminalid;
        private TextView label8;
        private EditText textBoxRResponseText;
        private TextView label7;
        private EditText textBoxRResponseCode;
        private TextView label6;
        private EditText textBoxRAmount;
        private TextView label5;
        private EditText textBoxRRawMSG;
        private Button Refundbutton;
        private EditText RefundTextbox;
        private TextView label17;
        private Button PreAuthbutton;
        private EditText PreAuthtextBox;
        private TextView label18;
        private Button Settlementbutton;
        private TextView label19;
        private Button Detailbutton;
        private TextView label20;
        private Button TotalReportbutton;
        private TextView label21;
        private Button Reprintbutton;
        private TextView label22;
        private CheckBox checkBoxTripleDesc;
        private TextView label26;
        private EditText textBoxCardHolderName;
        private TextView label25;
        private EditText textBoxLabel;
        private TextView label24;
        private EditText textBoxAID;
        private TextView label23;
        private EditText textBoxMerchantID;

        }

